おすすめ機能追加１_0613
hiromuller/tapyourbeer_ver3 pull request #14
Opened 2020-06-13 12:22 UTC by mikiya118

おすすめ機能追加１回目

2020-06-15 06:29 UTC, hiromuller requested changes

2020-06-15 06:29 UTC, hiromuller commented on apps/search/services.py
> +import pprint
不要なので削除

2020-06-15 06:29 UTC, hiromuller commented on apps/search/views.py
> +    number_of_user_comments = SERVICES.selectNumnerofUserComments(request.user)
変数の名称が冗長。num_user_commentくらいでよい。
あと、関数名にタイプミスがあるので要修正。
また、コメント数が5個未満の場合、おすすめビール取得処理を行う必要がないので、
1.コメント数を取得
2. コメント数が5個以上の場合はおすすめビール取得処理を行い、cにrecommended_beerを入れる。5個未満の場合処理しない
としたほうが良い。

2020-06-15 06:29 UTC, hiromuller commented on apps/search/views.py
> +    c.update({'number_of_user_comments':number_of_user_comments})
不要。理由は↑のコメントを参照。

2020-06-15 06:29 UTC, hiromuller commented on apps/search/views.py
> +    c.update({'recommended_beer':recommended_beer})
処理の場所を要修正。理由は↑のコメント参照。

2020-06-15 06:29 UTC, hiromuller commented on apps/search/views.py
> +
謎の改行。要削除。

2020-06-15 06:29 UTC, hiromuller commented on templates/search/main_content.html
> +                  {% if number_of_user_comments >= 5 %}
「number_of_user_comments」の中身で判定するのではなく、
「recommended_beer」という要素があれば処理する、に変更する。
つまり
{% if recommended_beer %}
と書けば良い。

2020-06-15 06:29 UTC, hiromuller commented on templates/search/main_content.html
> +                <div class="thumbnail">
このdivはなんのためのdiv?特に理由がなければ削除。

2020-06-15 06:29 UTC, hiromuller commented on apps/search/services.py
> +        user_comment_list.extend(MODELS.Comment.objects.filter(user=user))
num_comment = len(MODELS.Comment.objects.filter(user=user.id))
で長さ取得可能。もっと簡単に書くなら
return len(MODELS.Comment.objects.filter(user=user.id))
で良い。

2020-06-15 06:29 UTC, hiromuller commented on apps/common/views.py
> +        return MANAGER_VIEWS.mergeVenue(request)
おすすめ機能とは別の機能なのでpull requestは別々で行うこと。

2020-06-15 06:29 UTC, hiromuller commented on apps/search/services.py
> +        return comment_list
34行目-38行目でなにをしようとしているかわからない。
一度処理を文章で書いて説明してほしい。

2020-06-15 06:29 UTC, hiromuller commented on apps/search/services.py
> +        specialness_avelage = sum(specialness_value_list)/len(specialness_value_list)
62行目〜67行目まで、アベレージのスペルが間違っている。

2020-06-15 06:29 UTC, hiromuller commented on apps/search/services.py
> +        average_list = [bitterness_avelage, aroma_avelage, body_avelage, drinkability_avelage, pressure_avelage, specialness_avelage]
リスト型ではなくディクショナリ型にしたほうが良い。
リストだと順番を覚えて置かなければいけないが、ディクショナリ型であればキーを指定して値が取得可能となるので、わかりやすい。
つまり
average = {'bitterness':bitterness_avelage, 'aroma':arp,a_avelage,,,,}
という感じ。

2020-06-15 06:29 UTC, hiromuller commented on apps/search/services.py
> +        return MODELS.Beer.objects.get(id=recommended_beer_id)
79行目〜102行目まで、なにをやりたいのか文章にして説明してほしい。

2020-06-15 14:37 UTC, mikiya118 commented on apps/search/services.py
> +        return comment_list
１．userのoverall=5の評価のコメントをランダムに30件抽出→comment_listに追加
２．上記をoverall=5~1と下げて繰り返してcomment_listに追加（comment_listには最大30件x5回=150件コメントが入る）
３．コメントリストの31件以降を削除

2020-06-15 15:15 UTC, mikiya118 commented on apps/search/services.py
> +        return MODELS.Beer.objects.get(id=recommended_beer_id)
ユーザのコメントリストから求めた5大評価の平均値（user_average_list）と、
ランダムに100件取得したビール（beer_list）について、それぞれのビールの5大評価（beer_evaluation_elements_list）の差の絶対値を求め、5つの値の和を求めた。
5つの値の和が小さいほどユーザの平均値に近いため、ユーザーの好みに近いと判断し、おすすめビールとした。

2020-06-16 01:01 UTC, hiromuller commented on apps/search/services.py
> +        return comment_list
では、overall=5で３０件取得できた場合、結局forから抜けたあとに３０件目以降は削除してしまうので無駄な処理が発生している。overall=5 と overall=4の合計が２０以上になった場合も、それ以降の必要のない処理が発生している。
３６行目の[:30]という処理についても、例えばoverall=5が40件存在した場合、30件までしか取得せずに次のoverall=4のコメントをリストにextendしてしまっているので、38行目の処理がdel comment_list[35:]とかに変更した場合は理屈が合わなくなってしまう。
ので、
　１．「filterで持ってきた瞬間に30件にする」というところにはこだわらない（３８行目で結局長さ処理しているので）
　２．for文の中でcomment_list[]の長さが３０件以上になったときにbreakする。
という処理にすれば良い。

2020-06-16 01:13 UTC, hiromuller requested changes

2020-06-16 01:13 UTC, hiromuller commented on apps/search/services.py
> +        return MODELS.Beer.objects.get(id=recommended_beer_id)
了解。
ではこの処理に基づいて追加の修正点書きます。

2020-06-16 01:13 UTC, hiromuller commented on apps/search/services.py
> +        recommended_beer_id = beer_list[recommended_beertasteavg_index].beer.id
102行目でMODELS.を使わなくても、１００行目のbeer_list[recommended_beertasteavg_index].beer　ですでにBeerオブジェクトは取得できている。

2020-06-16 01:13 UTC, hiromuller commented on apps/search/services.py
> +            beer_evaluation_elements_list.append(float(beer.specialness))
６９行目で作っているリストの中の値の順番と、ここの要素の順番に相違がある。

2020-06-23 07:24 UTC, hiromuller requested changes

2020-06-23 07:24 UTC, hiromuller commented on apps/search/views.py
> +    c.update({'num_user_comments':num_user_comments})
テンプレート側ではnum_user_commentsではなく、recommended_beerがあるかないかで判断可能なので、59行目は削除して良い。。

2020-06-23 07:24 UTC, hiromuller commented on templates/search/main_content.html
> +
{% endif %}

2020-06-23 07:24 UTC, hiromuller commented on templates/search/main_content.html
{% if recommended_beer %}
と書くと、recommended_beer変数が渡されている場合に表示され、渡されていない場合は表示されなくなる。

2020-06-23 09:42 UTC, hiromuller requested changes

2020-06-23 09:42 UTC, hiromuller commented on apps/search/views.py
> +        None
else: None は何もしない処理なので不要。

2020-06-23 09:42 UTC, hiromuller commented on apps/search/services.py
> +        average_list = {'bitterness_average':bitterness_average, 'aroma_average':aroma_average, 'body_average':body_average, 'drinkability_average':drinkability_average, 'pressure_average':pressure_a
型がリストではなくディクショナリなので、変数名もaverage_dict的なものに修正する

2020-06-23 09:42 UTC, hiromuller commented on apps/search/services.py
> +            user_average_list = calculateUserEvaluationAveragebyUserEvaluationValue(user)
返ってきている値がリスト型ではなくディクショナリ型なので、変数名はuser_average_dictとする

2020-06-23 09:42 UTC, hiromuller commented on apps/search/services.py
> +                for a, b in zip(user_average_list.values(), beer_evaluation_elements_list):
ここで比較しているものはディクショナリ型とリスト型のものとなる。
違う型を同じ型のように扱うと後で見返したときに混乱するので、beer_evaluation_elements_listはディクショナリ型にしよう。比較方法もインデックス順ではなくディクショナリのキーで引っ張ってきて比較したほうがわかりやすくて良い。

2020-06-23 09:42 UTC, hiromuller commented on apps/search/services.py
> +                beer_evaluation_elements_list = []
user_comment_dictと比較する変数を作っているので、比較先の型に合わせるためにリストじゃなくてディクショナリ型にする。
beer_evaluation_elements_dict = {}
beer_evaluation_elements_dict.update({'bitterness':beer.bitterness})
beer_evaluation_elements_dict.update({'aroma':beer.aroma})
.
.
みたいな感じ

2020-06-23 09:42 UTC, hiromuller commented on apps/search/services.py
> +            None
else: None　は何もしないので、削除する

2020-07-07 14:18 UTC, merged